

default_platform(:android)

platform :android do
  desc "Lan for Android Firebase App Distribution"
  lane :firebase_distribution do
    # Run shell commands separately
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    # Firebase App Distribution configuration
    firebase_app_distribution(
      app: "1:321253441126:android:3dd31da1dae243cd1337a7",
      firebase_cli_token: "1//03Oap_A6gmjlpCgYIARAAGAMSNwF-L9IrJZNmfKCtepmmaIYTcKduh6XqKhiNMFMzl4eI8Y5pqUO6ATHGT5Kk6x53MfGbJqxtDmA",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "aboodshban@gmail.com",
      release_notes: "This is a new release"
    )
  end
end
