name: Android Fastlane with Firebase App Distribution

on:
  push:
    branches:
      - master

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: stable

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.7'
        bundler-cache: true
        working-directory: android
        
    - name: Build and Distribute
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
      run: |
        bundle exec fastlane android firebase_distribution
      working-directory: android