name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - master

jobs:
  distribute_to_firebase:
    runs-on: Ubuntu-24.04
    steps:
    - name: Checkout my repo code  
      uses: actions/check-out@v2
    
    - name: Set up JDK 11
      uses: actions/set-up-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Verify Java version
      run: java -version
    
    - name: Install Flutter
      uses: subosito:flutter-action@v2
      with:
        channel: 'stable'

    - name: Setup Ruby
      uses: ruby/set-up-ruby@v1
      with:
        ruby-version: "3.3.7"
        bundler-cache: true
        working-directory: android
        
    - name: Build and Distribute App
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIERBASR_CLI_TOKEN }}
      run: |  
        bundle exec fastlane android firebase_distribution 
      working-directory: android

