name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - master

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my repo code  
      uses: actions/checkout@v2
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
    
    - name: Verify Java version
      run: java-version
    
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        version: "3.19.2"
        flutter-version: "3.19.2"

    - name: Flutter doctor
      run: flutter doctor -v
    
    - name: Install dependencies
      run: flutter pub get

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3.7"
        bundler-cache: true
        working-directory: android
        
    - name: Build and Distribute App
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIERBASR_CLI_TOKEN }}
      run: |  
        bundle exec fastlane android firebase_distribution 
      working-directory: android

